apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" .}}-svc
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
